version: "3"

services:
  gateway:
    image: "nestjs-restaurant/gateway"
    restart: always
    ports:
      - 9500:3000
    environment:
      - MENU_SERVICE_URL_WITH_PORT=${MENU_SERVICE}:3000
      - KITCHEN_SERVICE_URL_WITH_PORT=${KITCHEN_SERVICE}:3000
      - DINING_SERVICE_URL_WITH_PORT=${DINING_SERVICE}:3000
      - REACT_UI_WAITER_URL_WITH_PORT=${REACT_UI_WAITER}:80
    networks:
      - nestjs-restaurant-network
networks:
  nestjs-restaurant-network:
    driver: bridge
